### ISSUE TITLE
General Corrections

### ISSUE THREAD

**Issue by vendforce** [ipserc/zhavam#6]
Can you confirm ?

1 ) Go to ayuda/about in the drop down menu and try click the close button it doesn't close nor the license  button work, I know its a minor detail , you can always close the window by the x in the corner, but since there's a button there it should work or just remove it and let people close the window with the x, either way just a little bug 

2 ) ayuda in drop down needs to changed into English to help 

The other issue I have with the song recognition , the fix is run a song click the button let it find a result then to make sure it has identify it correctly click it again , I've noticed it got the song wrong a few times but If I let the song play on and click it again it yields a different result being the correct result

thanks keep up the great work !!!

**Comment by ipserc** [comment]
Hello vendforce, sorry for not responding before.
The "ayuda" / about malfunction is a problem with the GTKDialogBox of the GTK (Version: 3.22.30-1ubuntu4) that I have not been able to solve yet.
I will be uploading version 1.4 shortly, with some changes, among others I have reactivated the command line mode with which I started to program zhavam, which can be executed from a console.
Thank you for your comments.
